entryPoints:
  web:
    # Listen on port 8081 for incoming requests
    address: :8081

providers:
  # Enable the file provider to define routers / middlewares / services in file
  file:
    directory: /etc/traefik-config

log:
  level: DEBUG

pilot:
  token: a07449cc-8cc0-4f79-b51b-cac7fb178bb6

experimental:
  devPlugin:
    goPath: /plugins/
    moduleName: github.com/lvlsgroup/plugin-simplecache-lvlsgroup
